# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/polzovatel/Desktop/C++Project/pms-library

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/polzovatel/Desktop/C++Project/pms-library

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/opt/homebrew/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/polzovatel/Desktop/C++Project/pms-library/CMakeFiles /Users/polzovatel/Desktop/C++Project/pms-library//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/polzovatel/Desktop/C++Project/pms-library/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named core

# Build rule for target.
core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 core
.PHONY : core

# fast build rule for target.
core/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/build
.PHONY : core/fast

#=============================================================================
# Target rules for targets named utils

# Build rule for target.
utils: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 utils
.PHONY : utils

# fast build rule for target.
utils/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/build
.PHONY : utils/fast

#=============================================================================
# Target rules for targets named pms_app

# Build rule for target.
pms_app: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pms_app
.PHONY : pms_app

# fast build rule for target.
pms_app/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pms_app.dir/build.make CMakeFiles/pms_app.dir/build
.PHONY : pms_app/fast

#=============================================================================
# Target rules for targets named test_DateTime

# Build rule for target.
test_DateTime: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_DateTime
.PHONY : test_DateTime

# fast build rule for target.
test_DateTime/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_DateTime.dir/build.make tests/CMakeFiles/test_DateTime.dir/build
.PHONY : test_DateTime/fast

#=============================================================================
# Target rules for targets named test_Room

# Build rule for target.
test_Room: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_Room
.PHONY : test_Room

# fast build rule for target.
test_Room/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_Room.dir/build.make tests/CMakeFiles/test_Room.dir/build
.PHONY : test_Room/fast

#=============================================================================
# Target rules for targets named test_BookingFlow

# Build rule for target.
test_BookingFlow: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_BookingFlow
.PHONY : test_BookingFlow

# fast build rule for target.
test_BookingFlow/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_BookingFlow.dir/build.make tests/CMakeFiles/test_BookingFlow.dir/build
.PHONY : test_BookingFlow/fast

src/core/Billing.o: src/core/Billing.cpp.o
.PHONY : src/core/Billing.o

# target to build an object file
src/core/Billing.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/core/Billing.cpp.o
.PHONY : src/core/Billing.cpp.o

src/core/Billing.i: src/core/Billing.cpp.i
.PHONY : src/core/Billing.i

# target to preprocess a source file
src/core/Billing.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/core/Billing.cpp.i
.PHONY : src/core/Billing.cpp.i

src/core/Billing.s: src/core/Billing.cpp.s
.PHONY : src/core/Billing.s

# target to generate assembly for a file
src/core/Billing.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/core/Billing.cpp.s
.PHONY : src/core/Billing.cpp.s

src/core/Booking.o: src/core/Booking.cpp.o
.PHONY : src/core/Booking.o

# target to build an object file
src/core/Booking.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/core/Booking.cpp.o
.PHONY : src/core/Booking.cpp.o

src/core/Booking.i: src/core/Booking.cpp.i
.PHONY : src/core/Booking.i

# target to preprocess a source file
src/core/Booking.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/core/Booking.cpp.i
.PHONY : src/core/Booking.cpp.i

src/core/Booking.s: src/core/Booking.cpp.s
.PHONY : src/core/Booking.s

# target to generate assembly for a file
src/core/Booking.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/core/Booking.cpp.s
.PHONY : src/core/Booking.cpp.s

src/core/DateTime.o: src/core/DateTime.cpp.o
.PHONY : src/core/DateTime.o

# target to build an object file
src/core/DateTime.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/core/DateTime.cpp.o
.PHONY : src/core/DateTime.cpp.o

src/core/DateTime.i: src/core/DateTime.cpp.i
.PHONY : src/core/DateTime.i

# target to preprocess a source file
src/core/DateTime.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/core/DateTime.cpp.i
.PHONY : src/core/DateTime.cpp.i

src/core/DateTime.s: src/core/DateTime.cpp.s
.PHONY : src/core/DateTime.s

# target to generate assembly for a file
src/core/DateTime.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/core/DateTime.cpp.s
.PHONY : src/core/DateTime.cpp.s

src/core/Guest.o: src/core/Guest.cpp.o
.PHONY : src/core/Guest.o

# target to build an object file
src/core/Guest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/core/Guest.cpp.o
.PHONY : src/core/Guest.cpp.o

src/core/Guest.i: src/core/Guest.cpp.i
.PHONY : src/core/Guest.i

# target to preprocess a source file
src/core/Guest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/core/Guest.cpp.i
.PHONY : src/core/Guest.cpp.i

src/core/Guest.s: src/core/Guest.cpp.s
.PHONY : src/core/Guest.s

# target to generate assembly for a file
src/core/Guest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/core/Guest.cpp.s
.PHONY : src/core/Guest.cpp.s

src/core/Housekeeping.o: src/core/Housekeeping.cpp.o
.PHONY : src/core/Housekeeping.o

# target to build an object file
src/core/Housekeeping.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/core/Housekeeping.cpp.o
.PHONY : src/core/Housekeeping.cpp.o

src/core/Housekeeping.i: src/core/Housekeeping.cpp.i
.PHONY : src/core/Housekeeping.i

# target to preprocess a source file
src/core/Housekeeping.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/core/Housekeeping.cpp.i
.PHONY : src/core/Housekeeping.cpp.i

src/core/Housekeeping.s: src/core/Housekeeping.cpp.s
.PHONY : src/core/Housekeeping.s

# target to generate assembly for a file
src/core/Housekeeping.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/core/Housekeeping.cpp.s
.PHONY : src/core/Housekeeping.cpp.s

src/core/Resource.o: src/core/Resource.cpp.o
.PHONY : src/core/Resource.o

# target to build an object file
src/core/Resource.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/core/Resource.cpp.o
.PHONY : src/core/Resource.cpp.o

src/core/Resource.i: src/core/Resource.cpp.i
.PHONY : src/core/Resource.i

# target to preprocess a source file
src/core/Resource.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/core/Resource.cpp.i
.PHONY : src/core/Resource.cpp.i

src/core/Resource.s: src/core/Resource.cpp.s
.PHONY : src/core/Resource.s

# target to generate assembly for a file
src/core/Resource.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/core/Resource.cpp.s
.PHONY : src/core/Resource.cpp.s

src/core/Room.o: src/core/Room.cpp.o
.PHONY : src/core/Room.o

# target to build an object file
src/core/Room.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/core/Room.cpp.o
.PHONY : src/core/Room.cpp.o

src/core/Room.i: src/core/Room.cpp.i
.PHONY : src/core/Room.i

# target to preprocess a source file
src/core/Room.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/core/Room.cpp.i
.PHONY : src/core/Room.cpp.i

src/core/Room.s: src/core/Room.cpp.s
.PHONY : src/core/Room.s

# target to generate assembly for a file
src/core/Room.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/core/Room.cpp.s
.PHONY : src/core/Room.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pms_app.dir/build.make CMakeFiles/pms_app.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pms_app.dir/build.make CMakeFiles/pms_app.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pms_app.dir/build.make CMakeFiles/pms_app.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/utils/ConfigParser.o: src/utils/ConfigParser.cpp.o
.PHONY : src/utils/ConfigParser.o

# target to build an object file
src/utils/ConfigParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/utils/ConfigParser.cpp.o
.PHONY : src/utils/ConfigParser.cpp.o

src/utils/ConfigParser.i: src/utils/ConfigParser.cpp.i
.PHONY : src/utils/ConfigParser.i

# target to preprocess a source file
src/utils/ConfigParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/utils/ConfigParser.cpp.i
.PHONY : src/utils/ConfigParser.cpp.i

src/utils/ConfigParser.s: src/utils/ConfigParser.cpp.s
.PHONY : src/utils/ConfigParser.s

# target to generate assembly for a file
src/utils/ConfigParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/utils/ConfigParser.cpp.s
.PHONY : src/utils/ConfigParser.cpp.s

src/utils/Logger.o: src/utils/Logger.cpp.o
.PHONY : src/utils/Logger.o

# target to build an object file
src/utils/Logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/utils/Logger.cpp.o
.PHONY : src/utils/Logger.cpp.o

src/utils/Logger.i: src/utils/Logger.cpp.i
.PHONY : src/utils/Logger.i

# target to preprocess a source file
src/utils/Logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/utils/Logger.cpp.i
.PHONY : src/utils/Logger.cpp.i

src/utils/Logger.s: src/utils/Logger.cpp.s
.PHONY : src/utils/Logger.s

# target to generate assembly for a file
src/utils/Logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/utils/Logger.cpp.s
.PHONY : src/utils/Logger.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... core"
	@echo "... pms_app"
	@echo "... test_BookingFlow"
	@echo "... test_DateTime"
	@echo "... test_Room"
	@echo "... utils"
	@echo "... src/core/Billing.o"
	@echo "... src/core/Billing.i"
	@echo "... src/core/Billing.s"
	@echo "... src/core/Booking.o"
	@echo "... src/core/Booking.i"
	@echo "... src/core/Booking.s"
	@echo "... src/core/DateTime.o"
	@echo "... src/core/DateTime.i"
	@echo "... src/core/DateTime.s"
	@echo "... src/core/Guest.o"
	@echo "... src/core/Guest.i"
	@echo "... src/core/Guest.s"
	@echo "... src/core/Housekeeping.o"
	@echo "... src/core/Housekeeping.i"
	@echo "... src/core/Housekeeping.s"
	@echo "... src/core/Resource.o"
	@echo "... src/core/Resource.i"
	@echo "... src/core/Resource.s"
	@echo "... src/core/Room.o"
	@echo "... src/core/Room.i"
	@echo "... src/core/Room.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/utils/ConfigParser.o"
	@echo "... src/utils/ConfigParser.i"
	@echo "... src/utils/ConfigParser.s"
	@echo "... src/utils/Logger.o"
	@echo "... src/utils/Logger.i"
	@echo "... src/utils/Logger.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

